# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34882b9fb8f1f8adbd5146b132ebc135f40474f67660f708d8d9c5f589232aec21768700030b8d82fedc9e3a365dad7cfe893e4a5870edb2ceb87718ce06ad3a

test:
  secret_key_base: 87e877dfb2b57fac642185b05aeeeebad71ae1e30974e1047ce8ceeb9d500b26cdb0f422d06d6fb4a15615c03370a2b1f532c7e44bd70245c0e313a9639c3a57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
